# from https://github.com/deepprinciple/HORM/blob/eval/train.py

# @package _global_

model:
  name: "AlphaNet"
  num_targets: 1
  output_dim: 1
  readout: "sum"
  use_pbc: false
  direct_forces: false
  eps: 1.0e-06
  num_layers: 4
  hidden_channels: 128
  cutoff: 5.0
  num_radial: 64
  use_sigmoid: false
  head: 16
  a: 0.35
  pos_require_grad: true
  b: 0
  main_chi1: 32
  mp_chi1: 32
  chi2: 8
  hidden_channels_chi: 96
  has_dropout_flag: true
  has_norm_before_flag: true
  has_norm_after_flag: false
  reduce_mode: "sum"
  device: "cuda"
  compute_forces: true
  compute_stress: false

optimizer:
  lr: 5.0e-04
  betas:
    - 0.9
    - 0.999
  weight_decay: 0
  amsgrad: true

training:
  bz: 2
  num_workers: 48
  clip_grad: true
  gradient_clip_val: 0.1
  ema: false
  lr_schedule_type: "step"
  lr_schedule_config:
    gamma: 0.85
    step_size: 50