# @package _global_

# Configuration reconstructed from the HORM leftnet-df checkpoint.
# Metadata: {'device_count': None, 'epoch': 149, 'global_step': 120000}

model:
  name: LEFTNet-df
  act_fn: "swish"
  cutoff: 10.0
  ff: true
  for_conf: false
  hidden_channels: 196
  in_hidden_channels: 8
  in_node_nf: 8
  legacy: true
  num_layers: 6
  num_radial: 96
  pos_grad: false
  pos_require_grad: true
  reflect_equiv: true
  single_layer_output: true
  update: true

optimizer:
  amsgrad: true
  betas:
    - 0.9
    - 0.999
  lr: 1.0e-05
  weight_decay: 0

training:
  bz: 16
  clip_grad: true
  datadir: '/deepprinciple-proj-dev/datasets/transition-1x/'
  ema: false
  gradient_clip_val: null
  lr_schedule_type: null
  lr_schedule_config:
    gamma: 0.8
    step_size: 10
  num_workers: 0
  trn_path: '/ssd/Code/hip/data/sample_100.lmdb'
  val_path: '/ssd/Code/hip/data/sample_100.lmdb'
